### ISSUE TITLE
[Docs] 

### ISSUE THREAD

**Issue by catmaohphp** [zhaiyi000/tlm#2]
Hi, can you provide any examples of tuning a specific network (e.g., VGG16) using the pre-trained model on V100?

**Comment by zhaiyi000** [comment]
Hi, catmaohphp. You can refer to the "Getting Started Instructions" section in the README. There, we provide an example of compiling bert_base.

**Comment by zhaiyi000** [comment]
Now that there are no further questions, I am closing the issue.
