### ISSUE TITLE
Some questions on released dataset and results

### ISSUE THREAD

**Issue by lv2020** [zhaiyi000/tlm#3]
Thanks for your release of raw experimental results and model weight. But I meet a few questions when I repeat the experiments. I downloaded the data from https://drive.google.com/file/d/1MdOxSIBFqYl1pWWUmj18vm4AG4Sbly8Z/view. 

1. Missing Llama/GPT2 performance? When I run the meta_speedup_eval.py, I get the performance for 10 networks except Llama and GPT2. While there are 329 subgraph folders under meta/0_test_67, the paper claims that there are 364 subgraphs for TLM-Meta. It seems the released records are incomplete. Besides, does the Llama/GPT2 use the same config as in https://github.com/zhaiyi000/tlm/blob/main/python/tvm/meta_schedule/testing/relay_workload.py? 

2. What is the difference between 0_test_67 and all other 0_test_x under meta/meta_data/measure_data_v100? I find that the speedup_eval.py always uses the last one for testing.

**Comment by zhaiyi000** [comment]
Hi, lv2020,

1. You can uncomment llama and gpt2 in `meta/dataset_collect_models.py` and `meta/meta_common.py`. These experiments with llama and gpt2 were added later; the organization of related data files is somewhat messy and not fully sorted out.
2. As data collection progresses, the last one is continuously updated.

**Comment by lv2020** [comment]
Thanks for your quick response! In this case, do I need to retrain the model? Is the uploaded model trained on the full dataset or without Llama/GPT2?

**Comment by zhaiyi000** [comment]
The uploaded model was trained without Llama/GPT2. It would be better to retrain.

**Comment by lv2020** [comment]
Thanks for your help!

**Comment by zhaiyi000** [comment]
When retraining, it is not necessary to start from scratch; the training set can begin with the training set we uploaded.

**Comment by lv2020** [comment]
Hi, is it possible for you to upload the tuning records for GPT2 and Llama? I run TLM with the uploaded weight to generate tensor programs for GPT2 and Llama but ran out of retry_i in meta_gen_state.py and only got results of 14 subgraphs.
